language: csharp
solution: My-Profile
notifications:
  email:
    on_success: always
    on_failure: always
  slack: cgiwave6:1NqbLKzmuRjgH6YOBVndxtwR
mono: none
dotnet: 2.1
script:
  - dotnet restore
  - dotnet test My-Profile.Tests