version: "2"
services:
  knowledge-graph:
    build: .
    ports:
      - "5003:5003"
    depends_on:
      - neo4j
      - rabbitmq
  neo4j:
    image: neo4j:latest
    ports:
      - "17474:7474"
      - "17687:7687"
    environment:
      - NEO4J_AUTH=neo4j/qwertyuiop
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_bolt_listen__address=:7687
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=achausername
      - RABBITMQ_DEFAULT_PASS=strongpassword
