version: "2"
services:
    sme:
        build: .
        ports:
            - "15000:5000"
        depends_on:
            - neo4j
    neo4j:
        image: neo4j:latest
        ports:
            - "17474:7474"
            - "17687:7687"
        environment:
            - NEO4J_AUTH=neo4j/qwertyuiop
            - NEO4J_dbms_connector_http_listen__address=:7474
            # - NEO4J_dbms_connector_https_listen__address=:6477
            - NEO4J_dbms_connector_bolt_listen__address=:7687