// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProfile;

namespace myprofile.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20181103095938_myprof5")]
    partial class myprof5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyProfile.LearningPlan", b =>
                {
                    b.Property<string>("LearningPlanId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserId");

                    b.HasKey("LearningPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("LP");
                });

            modelBuilder.Entity("MyProfile.User", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("Description");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Use");
                });

            modelBuilder.Entity("MyProfile.LearningPlan", b =>
                {
                    b.HasOne("MyProfile.User")
                        .WithMany("learningPlans")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
